
export const USERS_FOLLOW = 'FOLLOW'
export const USERS_UNFOLLOW = 'UNFOLLOW'
export const USERS_SET_USERS = 'SET_USERS'
export const USERS_SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const USERS_SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT'
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'