export const USERS_FOLLOW = 'FOLLOW'
export const USERS_UNFOLLOW = 'UNFOLLOW'
export const USERS_SET_USERS = 'SET_USERS'
export const USERS_SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const USERS_SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT'

export const USERS_TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING'
export const USERS_TOGGLE_IS_FOLLOWING_PROGRESS = 'TOGGLE_IS_FOLLOWING_PROGRESS'


export const PROFILE_ADD_POST = 'ADD-POST'
export const PROFILE_UPDATE_NEW_POST_TEXT = 'UPDATE-NEW-POST-TEXT'
export const PROFILE_SET_USER_PROFILE = 'SET_USER_PROFILE'
export const PROFILE_DELETE_POST = 'DELETE-POST'
export const PROFILE_SET_STATUS = 'SET_STATUS'
export const PROFILE_SAVE_PHOTO_SUCCESS = 'SAVE_PHOTO_SUCCESS'

export const AUTH_SET_USER_DATA = 'SET_USER_DATA'

export const APP_INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'

export const DIALOGS_SEND_MESSAGE = 'SEND_MESSAGE'
